version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install -g aws-cdk@latest
      - npm install

  build:
    commands:
      - echo "Building project..."
      - npm run build
      - echo "Synthesizing CDK..."
      - cdk synth

artifacts:
  files:
    - '**/*'
